CREATE DATABASE stepupdb;

-- DDL (Create, alter, drop)
USE stepupdb;

-- Creating the 'book' table
CREATE TABLE IF NOT EXISTS book (
    book_id INT,
    book_name VARCHAR(120) NOT NULL,
    author VARCHAR(120),
    publisher VARCHAR(120),
    no_of_copies INT,
    category VARCHAR(20),
    store_location VARCHAR(120),
    price INT,
    CONSTRAINT PRIMARY KEY pkey_book(book_id)
);

-- DML (delete, update, insert, select)
-- Inserting 100 sample records into the 'book' table
INSERT INTO book (book_id, book_name, author, publisher, no_of_copies, category, store_location, price) VALUES
(1, 'The Great Gatsby', 'F. Scott Fitzgerald', 'Scribner', 10, 'Fiction', 'Aisle 1', 15),
(2, 'To Kill a Mockingbird', 'Harper Lee', 'J.B. Lippincott & Co.', 7, 'Fiction', 'Aisle 2', 12),
(3, '1984', 'George Orwell', 'Secker & Warburg', 5, 'Dystopian', 'Aisle 3', 18),
(4, 'Moby-Dick', 'Herman Melville', 'Harper & Brothers', 3, 'Classic', 'Aisle 4', 20),
(5, 'The Catcher in the Rye', 'J.D. Salinger', 'Little, Brown and Company', 8, 'Fiction', 'Aisle 1', 10),
(6, 'Pride and Prejudice', 'Jane Austen', 'T. Egerton', 12, 'Romance', 'Aisle 5', 14),
(7, 'The Hobbit', 'J.R.R. Tolkien', 'George Allen & Unwin', 6, 'Fantasy', 'Aisle 6', 22),
(8, 'War and Peace', 'Leo Tolstoy', 'The Russian Messenger', 4, 'Historical', 'Aisle 7', 25),
(9, 'The Odyssey', 'Homer', 'Penguin Classics', 9, 'Epic', 'Aisle 8', 17),
(10, 'Crime and Punishment', 'Fyodor Dostoevsky', 'The Russian Messenger', 7, 'Philosophical', 'Aisle 9', 19),
(11, 'The Brothers Karamazov', 'Fyodor Dostoevsky', 'The Russian Messenger', 6, 'Philosophical', 'Aisle 9', 21),
(12, 'Les Misérables', 'Victor Hugo', 'A. Lacroix', 5, 'Historical', 'Aisle 10', 23),
(13, 'The Divine Comedy', 'Dante Alighieri', 'John Murray', 7, 'Epic', 'Aisle 8', 26),
(14, 'The Iliad', 'Homer', 'Penguin Classics', 8, 'Epic', 'Aisle 8', 16),
(15, 'Ulysses', 'James Joyce', 'Shakespeare and Company', 4, 'Modernist', 'Aisle 11', 20),
(16, 'Don Quixote', 'Miguel de Cervantes', 'Francisco de Robles', 3, 'Classic', 'Aisle 4', 24),
(17, 'Brave New World', 'Aldous Huxley', 'Chatto & Windus', 7, 'Dystopian', 'Aisle 3', 18),
(18, 'The Sound and the Fury', 'William Faulkner', 'Jonathan Cape and Harrison Smith', 5, 'Modernist', 'Aisle 11', 14),
(19, 'The Lord of the Rings', 'J.R.R. Tolkien', 'George Allen & Unwin', 9, 'Fantasy', 'Aisle 6', 28),
(20, 'The Sun Also Rises', 'Ernest Hemingway', 'Charles Scribner\'s Sons', 6, 'Fiction', 'Aisle 2', 16),
(21, 'The Stranger', 'Albert Camus', 'Gallimard', 10, 'Philosophical', 'Aisle 9', 17),
(22, 'Heart of Darkness', 'Joseph Conrad', 'Blackwood\'s Magazine', 4, 'Fiction', 'Aisle 1', 13),
(23, 'Invisible Man', 'Ralph Ellison', 'Random House', 8, 'Fiction', 'Aisle 1', 19),
(24, 'The Grapes of Wrath', 'John Steinbeck', 'The Viking Press', 7, 'Historical', 'Aisle 10', 20),
(25, 'Dracula', 'Bram Stoker', 'Archibald Constable and Company', 6, 'Gothic', 'Aisle 12', 18),
(26, 'The Old Man and the Sea', 'Ernest Hemingway', 'Charles Scribner\'s Sons', 5, 'Fiction', 'Aisle 2', 14),
(27, 'The Call of the Wild', 'Jack London', 'Macmillan', 8, 'Adventure', 'Aisle 13', 12),
(28, 'Frankenstein', 'Mary Shelley', 'Lackington, Hughes, Harding, Mavor & Jones', 9, 'Gothic', 'Aisle 12', 16),
(29, 'A Tale of Two Cities', 'Charles Dickens', 'Chapman & Hall', 10, 'Historical', 'Aisle 10', 17),
(30, 'Anna Karenina', 'Leo Tolstoy', 'The Russian Messenger', 3, 'Romance', 'Aisle 5', 24),
(31, 'Gone with the Wind', 'Margaret Mitchell', 'Macmillan', 7, 'Historical', 'Aisle 10', 23),
(32, 'Wuthering Heights', 'Emily Brontë', 'Thomas Cautley Newby', 4, 'Romance', 'Aisle 5', 15),
(33, 'Jane Eyre', 'Charlotte Brontë', 'Smith, Elder & Co.', 6, 'Romance', 'Aisle 5', 17),
(34, 'The Scarlet Letter', 'Nathaniel Hawthorne', 'Ticknor, Reed & Fields', 5, 'Historical', 'Aisle 10', 12),
(35, 'Great Expectations', 'Charles Dickens', 'Chapman & Hall', 8, 'Fiction', 'Aisle 2', 16),
(36, 'Lolita', 'Vladimir Nabokov', 'Olympia Press', 7, 'Fiction', 'Aisle 1', 20),
(37, 'Beloved', 'Toni Morrison', 'Alfred A. Knopf', 5, 'Historical', 'Aisle 10', 21),
(38, 'Fahrenheit 451', 'Ray Bradbury', 'Ballantine Books', 9, 'Dystopian', 'Aisle 3', 18),
(39, 'Catch-22', 'Joseph Heller', 'Simon & Schuster', 6, 'Satire', 'Aisle 14', 19),
(40, 'Slaughterhouse-Five', 'Kurt Vonnegut', 'Delacorte Press', 4, 'Satire', 'Aisle 14', 22),
(41, 'Of Mice and Men', 'John Steinbeck', 'Covici Friede', 7, 'Fiction', 'Aisle 2', 10),
(42, 'On the Road', 'Jack Kerouac', 'Viking Press', 6, 'Fiction', 'Aisle 2', 15),
(43, 'A Clockwork Orange', 'Anthony Burgess', 'William Heinemann', 5, 'Dystopian', 'Aisle 3', 14),
(44, 'One Hundred Years of Solitude', 'Gabriel García Márquez', 'Harper & Row', 10, 'Magical Realism', 'Aisle 15', 25),
(45, 'The Metamorphosis', 'Franz Kafka', 'Kurt Wolff Verlag', 6, 'Fiction', 'Aisle 1', 13),
(46, 'The Picture of Dorian Gray', 'Oscar Wilde', 'Ward, Lock & Co.', 8, 'Gothic', 'Aisle 12', 16),
(47, 'The Road', 'Cormac McCarthy', 'Alfred A. Knopf', 7, 'Dystopian', 'Aisle 3', 18),
(48, 'The Catcher in the Rye', 'J.D. Salinger', 'Little, Brown and Company', 8, 'Fiction', 'Aisle 1', 10),
(49, 'Madame Bovary', 'Gustave Flaubert', 'Michel Lévy Frères', 4, 'Romance', 'Aisle 5', 22),
(50, 'The Count of Monte Cristo', 'Alexandre Dumas', 'Pierre-Jules Hetzel', 9, 'Adventure', 'Aisle 13', 23),
(51, 'The Three Musketeers', 'Alexandre Dumas', 'Baudry', 6, 'Adventure', 'Aisle 13', 21),
(52, 'Treasure Island', 'Robert Louis Stevenson', 'Cassell and Company', 5, 'Adventure', 'Aisle 13', 14),
(53, 'Dr. Jekyll and Mr. Hyde', 'Robert Louis Stevenson', 'Longmans, Green & Co.', 8, 'Gothic', 'Aisle 12', 19),
(54, 'The Little Prince', 'Antoine de Saint-Exupéry', 'Reynal & Hitchcock', 10, 'Fiction', 'Aisle 1', 12),
(55, 'Alice\'s Adventures in Wonderland', 'Lewis Carroll', 'Macmillan', 7, 'Fantasy', 'Aisle 6', 18),
(56, 'The Adventures of Huckleberry Finn', 'Mark Twain', 'Charles L. Webster And Company', 9, 'Adventure', 'Aisle 13', 20),
(57, 'The Adventures of Tom Sawyer', 'Mark Twain', 'American Publishing Company', 6, 'Adventure', 'Aisle 13', 15),
(58, 'The Phantom of the Opera', 'Gaston Leroux', 'Pierre Lafitte', 4, 'Gothic', 'Aisle 12', 14),
(59, 'Journey to the Center of the Earth', 'Jules Verne', 'Pierre-Jules Hetzel', 8, 'Science Fiction', 'Aisle 16', 19),
(60, 'Twenty Thousand Leagues Under the Sea', 'Jules Verne', 'Pierre-Jules Hetzel', 7, 'Science Fiction', 'Aisle 16', 21),
(61, 'The War of the Worlds', 'H.G. Wells', 'William Heinemann', 10, 'Science Fiction', 'Aisle 16', 22),
(62, 'The Time Machine', 'H.G. Wells', 'William Heinemann', 6, 'Science Fiction', 'Aisle 16', 16),
(63, 'A Wrinkle in Time', 'Madeleine L\'Engle', 'Farrar, Straus & Giroux', 9, 'Science Fiction', 'Aisle 16', 13),
(64, 'The Martian', 'Andy Weir', 'Crown Publishing Group', 8, 'Science Fiction', 'Aisle 16', 24),
(65, 'Dune', 'Frank Herbert', 'Chilton Books', 7, 'Science Fiction', 'Aisle 16', 25),
(66, 'Foundation', 'Isaac Asimov', 'Gnome Press', 5, 'Science Fiction', 'Aisle 16', 22),
(67, 'Ender\'s Game', 'Orson Scott Card', 'Tor Books', 4, 'Science Fiction', 'Aisle 16', 21),
(68, 'The Hunger Games', 'Suzanne Collins', 'Scholastic Press', 10, 'Dystopian', 'Aisle 3', 12),
(69, 'Divergent', 'Veronica Roth', 'Katherine Tegen Books', 9, 'Dystopian', 'Aisle 3', 15),
(70, 'The Maze Runner', 'James Dashner', 'Delacorte Press', 6, 'Dystopian', 'Aisle 3', 18),
(71, 'The Giver', 'Lois Lowry', 'Houghton Mifflin', 7, 'Dystopian', 'Aisle 3', 13),
(72, 'The Handmaid\'s Tale', 'Margaret Atwood', 'McClelland and Stewart', 5, 'Dystopian', 'Aisle 3', 17),
(73, 'The Name of the Wind', 'Patrick Rothfuss', 'DAW Books', 8, 'Fantasy', 'Aisle 6', 20),
(74, 'Mistborn', 'Brandon Sanderson', 'Tor Books', 7, 'Fantasy', 'Aisle 6', 19),
(75, 'The Way of Kings', 'Brandon Sanderson', 'Tor Books', 9, 'Fantasy', 'Aisle 6', 22),
(76, 'A Game of Thrones', 'George R.R. Martin', 'Bantam Books', 6, 'Fantasy', 'Aisle 6', 18),
(77, 'Harry Potter and the Sorcerer\'s Stone', 'J.K. Rowling', 'Bloomsbury', 10, 'Fantasy', 'Aisle 6', 23),
(78, 'Harry Potter and the Chamber of Secrets', 'J.K. Rowling', 'Bloomsbury', 7, 'Fantasy', 'Aisle 6', 20),
(79, 'Harry Potter and the Prisoner of Azkaban', 'J.K. Rowling', 'Bloomsbury', 8, 'Fantasy', 'Aisle 6', 19),
(80, 'Harry Potter and the Goblet of Fire', 'J.K. Rowling', 'Bloomsbury', 9, 'Fantasy', 'Aisle 6', 22),
(81, 'Harry Potter and the Order of the Phoenix', 'J.K. Rowling', 'Bloomsbury', 6, 'Fantasy', 'Aisle 6', 21),
(82, 'Harry Potter and the Half-Blood Prince', 'J.K. Rowling', 'Bloomsbury', 10, 'Fantasy', 'Aisle 6', 25),
(83, 'Harry Potter and the Deathly Hallows', 'J.K. Rowling', 'Bloomsbury', 9, 'Fantasy', 'Aisle 6', 24),
(84, 'The Golden Compass', 'Philip Pullman', 'Scholastic Press', 6, 'Fantasy', 'Aisle 6', 18),
(85, 'The Subtle Knife', 'Philip Pullman', 'Scholastic Press', 5, 'Fantasy', 'Aisle 6', 15),
(86, 'The Amber Spyglass', 'Philip Pullman', 'Scholastic Press', 4, 'Fantasy', 'Aisle 6', 14),
(87, 'The Wind-Up Bird Chronicle', 'Haruki Murakami', 'Shinchosha', 8, 'Fiction', 'Aisle 1', 22),
(88, 'Kafka on the Shore', 'Haruki Murakami', 'Shinchosha', 9, 'Fiction', 'Aisle 1', 21),
(89, 'Norwegian Wood', 'Haruki Murakami', 'Kodansha', 6, 'Fiction', 'Aisle 1', 18),
(90, 'The Dark Tower: The Gunslinger', 'Stephen King', 'Grant', 7, 'Fantasy', 'Aisle 6', 15),
(91, 'The Shining', 'Stephen King', 'Doubleday', 8, 'Horror', 'Aisle 17', 19),
(92, 'It', 'Stephen King', 'Viking Press', 10, 'Horror', 'Aisle 17', 23),
(93, 'Carrie', 'Stephen King', 'Doubleday', 5, 'Horror', 'Aisle 17', 14),
(94, 'Salem\'s Lot', 'Stephen King', 'Doubleday', 4, 'Horror', 'Aisle 17', 18),
(95, 'The Stand', 'Stephen King', 'Doubleday', 9, 'Horror', 'Aisle 17', 25),
(96, 'Misery', 'Stephen King', 'Viking Press', 6, 'Horror', 'Aisle 17', 20),
(97, 'The Haunting of Hill House', 'Shirley Jackson', 'Viking Press', 7, 'Horror', 'Aisle 17', 16),
(98, 'Dracula', 'Bram Stoker', 'Archibald Constable and Company', 10, 'Gothic', 'Aisle 12', 18),
(99, 'Rebecca', 'Daphne du Maurier', 'Victor Gollancz', 5, 'Gothic', 'Aisle 12', 20),
(100, 'The Woman in White', 'Wilkie Collins', 'All the Year Round', 6, 'Gothic', 'Aisle 12', 14);




